require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
require('./governance/runtime').validateRuntime();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const { Pool } = require('pg');
const app = express();
const PORT = process.env.BACKEND_PORT || 3001;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
app.locals.pool = pool;
const allowedOrigins = String(process.env.CLIENT_URL || 'http://localhost:3000').split(',').map((v) => v.trim());
app.use(helmet());
app.use(cors({ origin: (origin, cb) => !origin || allowedOrigins.includes(origin) ? cb(null, true) : cb(new Error('Origin not allowed')), credentials: true }));
app.use(express.json({ limit: '5mb' }));
const names = ['auth','outfits','styles','colors','trends','wardrobe','ratings','moodboards','stylist','fabrics','seasonal','bodytype','accessories','history','sustainable','celebrity','ai','calendar'];
names.forEach((name) => app.use(`/api/${name}`, require(`./routes/${name}`)));
const extensions = [['extensions','extensions'],['agentic-stylist','agenticStylist'],['virtual-wardrobe','virtualWardrobe'],['personal-color-analysis','personalColorAnalysis'],['sustainability-score','sustainabilityScore'],['rental-integration','rentalIntegration'],['style-evolution','styleEvolution'],['influencer-collab','influencerCollab'],['fit-return-risk','fitReturnRisk'],['custom-views','customViews']];
extensions.forEach(([mount, name]) => app.use(`/api/${mount}`, require(`./routes/${name}`)));
app.use('/api/governed-workflow', require('./governance/router')(pool));
app.get('/api/health', (_req, res) => res.json({ status: 'ok' }));
app.use('/api', (req, res) => res.status(404).json({ error: 'Not found', path: req.originalUrl }));
async function start() { await pool.query('SELECT 1'); app.listen(PORT, () => console.log(`Backend server running on port ${PORT}`)); }
if (require.main === module) start().catch((error) => { console.error('Startup failed:', error.message); process.exit(1); });
module.exports = app;
